# Generated by Django 2.2.4 on 2019-08-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicaFuenlabrada1Medidas',
            fields=[
                ('id_medida', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_sensor', models.IntegerField(blank=True, null=True)),
                ('tipo_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('id_mota', models.BigIntegerField(blank=True, null=True)),
                ('medida', models.FloatField(blank=True, null=True)),
                ('hora', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'clinica_fuenlabrada_1_medidas',
            },
        ),
        migrations.CreateModel(
            name='ClinicaFuenlabrada1Motas',
            fields=[
                ('id_mota', models.BigAutoField(primary_key=True, serialize=False)),
                ('mac', models.BigIntegerField(blank=True, null=True)),
                ('num_sensores', models.IntegerField(blank=True, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=20, null=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'clinica_fuenlabrada_1_motas',
            },
        ),
        migrations.CreateModel(
            name='ClinicaFuenlabrada1Sensores',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('id_mota', models.BigIntegerField(blank=True, null=True)),
                ('puerto', models.IntegerField(blank=True, null=True)),
                ('tipo_sensor', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('seq', models.BigIntegerField(blank=True, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'clinica_fuenlabrada_1_sensores',
            },
        ),
    ]
